### PR TITLE
Fix/dashboard url count

### LINKED ISSUE #127: [BUG] Remaining urls is not shown on the UI
### Issue Description
Currently, the URLs and remaining URLs heading is not shown on the UI so we need to fix this 

### Screenshots
image

### Reproducibility

 - [ ] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. 
2. 

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

### PR DESCRIPTION
**Pull request by vinit717**
## Issue Ticket Number

-   closes #127 

## Description

Fix remaining UI bug over user dashboard

**Breaking Changes**

-   [ ] Yes
-   [x] No

_If your feature introduces breaking changes or if something is missing, please mention the related issue tickets._

**Development Tested?**

-   [x] Yes
-   [ ] No

_Confirm whether the changes have been tested locally during development._

**Tested in Staging?**

-   [x] Yes
-   [ ] No

_Indicate whether the changes have been tested in the staging environment._

**Under Feature Flag**

-   [x] Yes
-   [ ] No

_Specify if the changes are currently under a feature flag._

**Database Changes**

-   [ ] Yes
-   [x] No

_Indicate whether the changes include modifications to the database._

### Screenshots

image

## Test Coverage

image

## Additional Notes

Include any additional notes, considerations, or explanations that might be helpful for reviewers.

### CODE REVIEW

File: src/components/Dashboard/dashboard-layout.tsx [hunk 1]
```diff
@@ -14,8 +14,8 @@ export const DashboardLayout = ({ remainingUrls, children }: DashboardLayoutProp
                 <div className="flex items-center pb-8 w-full justify-between">
                     <h1 className="text-3xl md:text-4xl xl:text-4xl text-center text-white font-semibold">Your URLs</h1>
 
-                    {remainingUrls && (
-                        <h4>
+                    {remainingUrls !== undefined && (
```
Comment (yesyash) [inline src/components/Dashboard/dashboard-layout.tsx:17]:
```suggestion
                    {!!remainingUrls && (
```
this will also check for null and 0 value

**Review by yesyash — APPROVED** [review]

**Review by Achintya-Chatterjee — APPROVED** [review]
